security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Presentation\DTO\Customer\CustomerDTO:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\Customer\Entity\Customer
                property: email
        oauth_hwi:
            id: hwi_oauth.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Presentation\Security\LoginFormAuthenticator
            oauth:
                resource_owners:
                    auth0: "/auth0/callback"
                login_path: /
                failure_path: /
                default_target_path: /list
                oauth_user_provider:
                    service: hwi_oauth.user.provider
            form_login:
                login_path: app_login
                check_path: app_login
            entry_point: form_login
            logout:
                path: app_logout
                # where to redirect after logout
                target: homepage
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: '^/quiz/*', roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
