parameters:
    app.secretToken: '%env(APP_SECRET)%'
    app.authorizationKey: '%env(AUTH_KEY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Presentation\Resolvers\QuestionAnswerDTOResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50}
    App\Infrastructure\Service\AuthService:
       arguments:
           $authToken: '%app.authorizationKey%'
    domen_customer.oauth.user.provider: 
        class: App\Presentation\Provider\CustomerEntityProvider
    App\Presentation\EventListener\CustomLogoutListener:
        tags:
            -   name: 'kernel.event_listener'
                event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
                dispatcher: security.event_dispatcher.main
                method: onLogoutEvent
        arguments:
            $quizSessionService: '@App\Domain\QuizSession\Service\QuizSessionService'
    App\Presentation\EventListener\CustomLoginListener:
        tags:
            -   name: 'kernel.event_listener'
                event: 'Symfony\Component\Security\Http\Event\LoginSuccessEvent'
                dispatcher: security.event_dispatcher.main
                method: onLoginEvent        
        arguments:
            $quizSessionService: '@App\Domain\QuizSession\Service\QuizSessionService'
