parameters:
    app.secretToken: '%env(APP_SECRET)%'
    app.authorizationKey: '%env(AUTH_KEY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Presentation\Resolvers\QuestionAnswerDTOResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50}
    App\Infractructure\Service\AuthService:
       arguments:
           $authToken: '%app.authorizationKey%'
           
           
